# Generated by Django 5.0.7 on 2026-08-23 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_enabled', models.BooleanField(default=True)),
                ('irrigation_enabled', models.BooleanField(default=True)),
                ('fertilizer_enabled', models.BooleanField(default=True)),
                ('crop_calendar_enabled', models.BooleanField(default=True)),
                ('market_enabled', models.BooleanField(default=True)),
                ('disease_enabled', models.BooleanField(default=True)),
                ('scheme_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
