# Generated by Django 5.0.7 on 2026-08-17 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('symptoms', models.TextField(blank=True)),
                ('possible_causes', models.TextField(blank=True)),
                ('recommended_actions', models.TextField(blank=True)),
                ('prevention_methods', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_detections/')),
                ('crop_hint', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('unavailable', 'Detection unavailable — no trained model yet'), ('success', 'Success'), ('failed', 'Processing failed')], default='unavailable', max_length=20)),
                ('predicted_disease', models.CharField(blank=True, max_length=150)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
