# Generated by Django 5.0.7 on 2026-08-13 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('land_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('soil_type', models.CharField(blank=True, choices=[('alluvial', 'Alluvial'), ('black', 'Black (Regur)'), ('red', 'Red'), ('laterite', 'Laterite'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('loamy', 'Loamy')], max_length=20)),
                ('irrigation_type', models.CharField(blank=True, choices=[('rainfed', 'Rain-fed'), ('canal', 'Canal'), ('borewell', 'Borewell'), ('drip', 'Drip'), ('sprinkler', 'Sprinkler')], max_length=20)),
                ('crops_grown', models.JSONField(blank=True, default=list)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu')], default='en', max_length=5)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
