# Generated by Django 5.0.7 on 2026-08-17 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irrigation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pesticide_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_yield', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_per_acre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue_per_acre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
