# Generated by Django 5.0.7 on 2026-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
