# Generated by Django 5.0.7 on 2026-08-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=150)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='per quintal', max_length=20)),
                ('recorded_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='crops.crop')),
            ],
            options={
                'ordering': ['-recorded_date'],
                'indexes': [models.Index(fields=['crop', 'recorded_date'], name='market_mark_crop_id_b85aaa_idx'), models.Index(fields=['market_name'], name='market_mark_market__951336_idx')],
            },
        ),
    ]
