# Generated by Django 5.0.7 on 2026-08-16 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sowing', 'Sowing'), ('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer application'), ('pest_observation', 'Pest/disease observation'), ('harvest', 'Harvest'), ('expense', 'Expense'), ('other', 'Other')], max_length=20)),
                ('crop_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
    ]
