# Generated by Django 5.0.7 on 2026-08-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('wind_kph', models.FloatField(blank=True, null=True)),
                ('rain_probability_percent', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('forecast', models.JSONField(blank=True, default=list)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(default='mock', max_length=30)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
